services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
  backend:
    build: .
    ports:
      - "5000:5050"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://admin:qwerty@mongo:27017
  frontend:
    build: ./public
    ports:
      - "8000:80"
    